#cloud-config
users:
  - name: trading
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICwBM0Il2wllzVOq8pVvA9V31ulcdnrYeaTH2QP2asEW data@nelor.com

packages:
  - python3-pip
  - python3-venv
  - git

runcmd:
  - mkdir -p /home/trading/bot/logs
  - chown -R trading:trading /home/trading/bot
  - sudo -u trading python3 -m venv /home/trading/bot/venv
  - sudo -u trading /home/trading/bot/venv/bin/pip install -r /home/trading/bot/requirements.schwab.txt
  - systemctl daemon-reload
  - systemctl enable schwab-bot
